name: intern_go
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you plan to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  file_picker: ^10.2.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.9
  firebase_storage: ^12.4.7
  multi_select_flutter: ^4.1.3
  carousel_slider: ^5.1.1
  google_fonts: ^6.2.1
  url_launcher: ^6.2.5
  flutter_gen_ai_chat_ui: ^2.3.0
  flutter_gemini: ^3.0.0
  animate_do: ^4.2.0
  glassmorphism: ^3.0.0
  flutter_animate: ^4.5.2
  flutter_staggered_animations: ^1.1.1
  lucide_icons: ^0.257.0
  confetti: ^0.8.0
  provider: ^6.1.5
  badges: ^3.1.2
  lottie: ^3.3.1
  http: ^1.4.0
  deepseek_api: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  integration_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.jpg" # <-- Make sure this file exists

flutter:
  uses-material-design: true

  assets:
    - assets/images/
